dataloader:
  evaluator: {_target_: detectron2.evaluation.COCOEvaluator, dataset_name: '${..test.dataset.names}', output_dir: ./wkdrs/ovdino_swin_tiny224_bert_base_24ep}
  test:
    _target_: detectron2.data.build_detection_test_loader
    dataset: {_target_: detectron2.data.get_detection_dataset_dicts, filter_empty: false, names: coco_2017_val_ovd}
    mapper:
      _target_: detrex.data.DetrDatasetMapper
      augmentation:
      - {_target_: detectron2.data.transforms.ResizeShortestEdge, max_size: 1333, short_edge_length: 800}
      augmentation_with_crop: null
      img_format: RGB
      is_train: false
      mask_on: false
    num_workers: 2
  train:
    _target_: detectron2.data.build_detection_train_loader
    dataset: {_target_: detectron2.data.get_detection_dataset_dicts, names: coco_2017_train_ovd_unipro}
    mapper:
      _target_: detrex.data.DetrDatasetMapper
      augmentation:
      - {_target_: detectron2.data.transforms.RandomFlip}
      - _target_: detectron2.data.transforms.ResizeShortestEdge
        max_size: 1333
        sample_style: choice
        short_edge_length: [480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800]
      augmentation_with_crop:
      - {_target_: detectron2.data.transforms.RandomFlip}
      - _target_: detectron2.data.transforms.ResizeShortestEdge
        sample_style: choice
        short_edge_length: [400, 500, 600]
      - _target_: detectron2.data.transforms.RandomCrop
        crop_size: [384, 600]
        crop_type: absolute_range
      - _target_: detectron2.data.transforms.ResizeShortestEdge
        max_size: 1333
        sample_style: choice
        short_edge_length: [480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800]
      img_format: RGB
      is_train: true
      mask_on: false
    num_workers: 16
    total_batch_size: 16
lr_multiplier:
  _target_: detectron2.solver.WarmupParamScheduler
  scheduler:
    _target_: fvcore.common.param_scheduler.MultiStepParamScheduler
    milestones: [82500, 90000]
    values: [1.0, 0.1]
  warmup_factor: 0.001
  warmup_length: 0.0
  warmup_method: linear
model:
  _target_: projects.ovdino.modeling.OVDINO
  aux_loss: true
  backbone:
    _target_: detectron2.modeling.SwinTransformer
    depths: [2, 2, 6, 2]
    drop_path_rate: 0.1
    embed_dim: 96
    num_heads: [3, 6, 12, 24]
    out_indices: [1, 2, 3]
    pretrain_img_size: 224
    window_size: 7
  box_noise_scale: 1.0
  criterion:
    _target_: projects.ovdino.modeling.DINOCriterion
    alpha: 0.25
    gamma: 2.0
    loss_class_type: focal_loss
    matcher: {_target_: detrex.modeling.HungarianMatcher, alpha: 0.25, cost_bbox: 5.0, cost_class: 2.0, cost_class_type: focal_loss_cost, cost_giou: 2.0, gamma: 2.0}
    num_classes: ${..num_classes}
    two_stage_binary_cls: false
    weight_dict: {loss_bbox: 5.0, loss_bbox_0: 5.0, loss_bbox_1: 5.0, loss_bbox_2: 5.0, loss_bbox_3: 5.0, loss_bbox_4: 5.0, loss_bbox_bcls_enc: 5.0, loss_bbox_dn: 5.0, loss_bbox_dn_0: 5.0, loss_bbox_dn_1: 5.0, loss_bbox_dn_2: 5.0, loss_bbox_dn_3: 5.0, loss_bbox_dn_4: 5.0, loss_bbox_dn_bcls_enc: 5.0, loss_bbox_dn_enc: 5.0, loss_bbox_enc: 5.0, loss_class: 1, loss_class_0: 1, loss_class_1: 1, loss_class_2: 1, loss_class_3: 1, loss_class_4: 1, loss_class_bcls_enc: 1, loss_class_dn: 1, loss_class_dn_0: 1, loss_class_dn_1: 1, loss_class_dn_2: 1, loss_class_dn_3: 1, loss_class_dn_4: 1, loss_class_dn_bcls_enc: 1, loss_class_dn_enc: 1, loss_class_enc: 1, loss_giou: 2.0, loss_giou_0: 2.0, loss_giou_1: 2.0, loss_giou_2: 2.0, loss_giou_3: 2.0, loss_giou_4: 2.0, loss_giou_bcls_enc: 2.0, loss_giou_dn: 2.0, loss_giou_dn_0: 2.0, loss_giou_dn_1: 2.0, loss_giou_dn_2: 2.0, loss_giou_dn_3: 2.0, loss_giou_dn_4: 2.0, loss_giou_dn_bcls_enc: 2.0, loss_giou_dn_enc: 2.0, loss_giou_enc: 2.0}
  device: cuda
  dn_number: 100
  embed_dim: 256
  inference_template: full
  input_format: RGB
  label_noise_ratio: 0.5
  language_backbone:
    _target_: detrex.modeling.BERTEncoder
    context_length: 48
    is_freeze: false
    is_normalize: false
    is_proj: false
    model_name: bert-base-uncased
    output_dim: 256
    padding_mode: longest
    pooling_mode: mean
    post_tokenize: true
    return_dict: false
    tokenizer_cfg: {tokenizer_name: bert-base-uncased}
  neck:
    _target_: detrex.modeling.ChannelMapper
    in_features: [p1, p2, p3]
    input_shapes:
      p1: !!python/object:detectron2.layers.shape_spec.ShapeSpec {channels: 192, height: null, stride: null, width: null}
      p2: !!python/object:detectron2.layers.shape_spec.ShapeSpec {channels: 384, height: null, stride: null, width: null}
      p3: !!python/object:detectron2.layers.shape_spec.ShapeSpec {channels: 768, height: null, stride: null, width: null}
    kernel_size: 1
    norm_layer: {_target_: torch.nn.GroupNorm, num_channels: 256, num_groups: 32}
    num_outs: 4
    out_channels: 256
  num_classes: 150
  num_queries: 900
  pixel_mean: [123.675, 116.28, 103.53]
  pixel_std: [58.395, 57.12, 57.375]
  position_embedding: {_target_: detrex.layers.PositionEmbeddingSine, normalize: true, num_pos_feats: 128, offset: -0.5, temperature: 10000}
  select_box_nums_for_evaluation: 300
  test_num_classes: 80
  transformer:
    _target_: projects.ovdino.modeling.DINOTransformer
    decoder: {_target_: projects.ovdino.modeling.DINOTransformerDecoder, attn_dropout: 0.0, embed_dim: 256, feedforward_dim: 2048, ffn_dropout: 0.0, num_feature_levels: '${..num_feature_levels}', num_heads: 8, num_layers: 6, return_intermediate: true, use_checkpoint: false}
    encoder: {_target_: projects.ovdino.modeling.DINOTransformerEncoder, attn_dropout: 0.0, embed_dim: 256, feedforward_dim: 2048, ffn_dropout: 0.0, num_feature_levels: '${..num_feature_levels}', num_heads: 8, num_layers: 6, post_norm: false, use_checkpoint: false}
    num_feature_levels: 4
    two_stage_num_proposals: ${..num_queries}
  vis_period: 0
optimizer:
  _target_: torch.optim.AdamW
  betas: [0.9, 0.999]
  lr: 0.0001
  params: {_target_: detectron2.solver.get_default_optimizer_params, base_lr: '${..lr}', lr_factor_func: !!python/name:None.%3Clambda%3E '', weight_decay_norm: 0.0}
  weight_decay: 0.0001
train:
  amp: {enabled: false}
  checkpointer: {max_to_keep: 100, period: 5000}
  clip_grad:
    enabled: true
    params: {max_norm: 0.1, norm_type: 2}
  ddp: {broadcast_buffers: false, find_unused_parameters: false, fp16_compression: false}
  device: cuda
  eval_period: 5000
  fast_dev_run: {enabled: false}
  init_checkpoint: ./inits/./swin/swin_tiny_patch4_window7_224.pth
  log_period: 50
  max_iter: 90000
  model_ema: {decay: 0.999, device: '', enabled: false, use_ema_weights_for_eval_only: false}
  output_dir: ./wkdrs/ovdino_swin_tiny224_bert_base_24ep
  seed: -1
  wandb:
    enabled: false
    params: {dir: ./wandb_output, name: detrex_experiment, project: detrex}
